### ISSUE TITLE
oocdoc comments

### ISSUE THREAD

**Issue by duckinator** [nixeagle/ooc-mode#1]
```
// normal comment
/// oocdoc comment
/* normal comment */
/** oocdoc comment */
```

oocdoc comments should be colored differently
hop to it :)

**Comment by nixeagle** [comment]
Just implemented single line oocdoc comments. Multiline will happen as soon as I figure out how to font-lock multiple lines without emacs overwriting random parts. The font-lock rules require a little more work for multiline comments as they work differently then singleline (performance reasons here).

**Comment by nixeagle** [comment]
And this is finally fixed! ;).
