### ISSUE TITLE
It can freeze emacs, too!

### ISSUE THREAD

**Issue by solson** [nixeagle/ooc-mode#19]
Since this bug is so hard to find and annoying to test, I'm going to just paste a file where I know it happened.

http://gist.github.com/475058

Go to line 150, add a comma after `LSHIFT`, and type `Scancode RSHIFT`... you probably won't be able to. It will make emacs temporarily non-responsive and you'll have to wait a while for it to come back.

To best recover, select the comma and the text after it and just delete it all at once. (You probably technically only need to remove the comma.)

**Comment by nixeagle** [comment]
Finally Closed by 224f09ab31b82df6f5f770b65d529765732e00f4, emacs no longer freezes! That was annoying to debug!
