### ISSUE TITLE
indentation after import lines

### ISSUE THREAD

**Issue by solson** [nixeagle/ooc-mode#2]
In the following code ooc-mode wants to indent the second line:

```
import ThingOne, ThingTwo
doSomething()
```

This only happens when there are commas in the import line. I assume the same thing happens with `use` and `include` directives.

**Comment by nixeagle** [comment]
Semi-fixed for the case where point immediately follows the import statement. Something like:
    import ThingOne, ThingTwo
    // some comment
        doSomething()

does not indent correctly (as my example shows). Put simply, any toplevel comment or string will confuse it

**Comment by nixeagle** [comment]
Indent all statement-cont matches to existing indention.

Closed by 2d8c4bd4812c6fa74d96b890a533f7bb37b423c6
