### ISSUE TITLE
ooc-mode flymake doesn't know about sourcepath

### ISSUE THREAD

**Issue by solson** [nixeagle/ooc-mode#3]
I compile oos with an explicit `-sourcepath=Src/Kernel` argument to rock. flymake doesn't know about this and so when it checks my files it can't find the ooc files I import.

**Comment by nixeagle** [comment]
This is done, I'll close this when documentation is written.

**Comment by nixeagle** [comment]
Ooc "projects" now work correctly. Requires rock HEAD as of about an hour ago. (VERY RECENT!)

Make sure to have rock commit
http://github.com/nddrylliog/rock/commit/03c0478fab76dfec61593b39871d3b071d312462
or later.

Closed by aa31d7be7f7052df5ca98750fbcdcddc04bc330d
